export {
  ProjectionError,
  SourceSelectionError,
  SourceDocumentError,
  type ProjectionErrorCode,
  type SourceDocumentErrorCode,
  type SourceSelectionErrorCode,
  type SourceSelectionField,
} from './errors.js';
export {
  createSourceDocument,
  normalizeSourceBody,
  parseSourceDocument,
  renderSourceDocument,
  validateSourceDocument,
} from './source-document.js';
export { createP2aPlanningProjector } from './p2a-planning-projector.js';
export { createP2aExecutionKnowledgeProjector } from './p2a-execution-projector.js';
export {
  createProjectSyncService,
  PROJECT_SYNC_SCHEMA_VERSION,
  ProjectSyncError,
  type CreateProjectSyncServiceOptions,
  type ProjectSyncDecisionCounts,
  type ProjectSyncErrorCode,
  type ProjectSyncFailurePhase,
  type HubProjectSyncInput,
  type LegacyProjectSyncInput,
  type ProjectSyncInput,
  type ProjectSyncPlanEntrySummary,
  type ProjectSyncPlanSummary,
  type ProjectSyncPort,
  type ProjectSyncRecoveryAction,
  type ProjectSyncSanitizationDiagnostics,
  type ProjectSyncSanitizationRuleSummary,
  type ProjectSyncSanitizationSource,
  type ProjectSyncSummary,
  type ProjectSyncWarning,
  type ProjectSyncWriteSummary,
} from './sync.js';
export { MAX_SYNC_SANITIZATION_DIAGNOSTIC_SOURCES } from './sync-sanitization-diagnostics.js';
export {
  EXECUTION_INCLUSION_POLICY_VERSION,
  EXECUTION_PROJECTION_PLAN_SCHEMA_VERSION,
  type CanonicalTaskLineage,
  type CreateP2aExecutionProjectorOptions,
  type ExecutionDecision,
  type ExecutionExcludeReason,
  type ExecutionIncludeReason,
  type ExecutionKnowledgeProjectorPort,
  type ExecutionProjectionApplyResult,
  type ExecutionProjectionInput,
  type ExecutionProjectionPlan,
  type ExecutionProjectionPlanEntry,
  type ExecutionProjectionWriteResult,
  type ExecutionQuarantineReason,
  type ExecutionReasonCode,
} from './execution-types.js';
export {
  type P2aArtifactAdapter,
  type P2aArtifactBinding,
  type P2aPlanningCandidate,
  type P2aPlanningSelection,
} from './p2a-artifacts.js';
export {
  PROJECTION_PLAN_SCHEMA_VERSION,
  type CreateP2aPlanningProjectorOptions,
  type PlanningDocumentKind,
  type P2aCompatibilityWarning,
  type P2aCompatibilityWarningCode,
  type PlanningProjectionInput,
  type PlanningProjectorPort,
  type ProjectionApplyResult,
  type ProjectionDecision,
  type ProjectionPlan,
  type ProjectionPlanEntry,
  type ProjectionReasonCode,
  type ProjectionWriteResult,
  type ProjectionWriteStatus,
  type RevisionTimestampPort,
  type RevisionTimestampRequest,
  type RevisionTimestampResolution,
  type TimestampSource,
} from './planning-types.js';
export {
  MAX_SOURCE_BODY_CHARS,
  SOURCE_DOCUMENT_SCHEMA_VERSION,
  SOURCE_DOCUMENT_V2_SCHEMA_VERSION,
  type BuildLoreSourceMetadata,
  type CreateSourceDocumentInput,
  type SourceDocument,
  type SourceType,
} from './types.js';
export {
  MAX_SOURCE_DECLARATIONS,
  MAX_SOURCE_MANIFEST_BYTES,
  MAX_SOURCE_PATH_LENGTH,
  SOURCE_COLLECTION_MANIFEST_SCHEMA_VERSION,
  SOURCE_COLLECTION_MANIFEST_V2_SCHEMA_VERSION,
  parseAnySourceCollectionManifest,
  parseSourceCollectionManifest,
  parseSourceCollectionManifestV2,
  sourceDeclarationDocumentKind,
  validateSourceSelectionPath,
  type AnySourceDeclaration,
  type SourceCollectionManifest,
  type SourceCollectionManifestV1,
  type SourceCollectionManifestV2,
  type SourceDeclaration,
  type SourceDocumentKind,
  type SourceDirectoryDeclaration,
  type SourceFileDeclaration,
  type SourceFileDeclarationV2,
  type SourceDirectoryDeclarationV2,
  type SourceDeclarationV2,
} from './source-manifest.js';
export {
  createSourceManagement,
  initializeSourceManifest,
  inspectSourceManifestInitialization,
  SOURCE_MANAGEMENT_SCHEMA_VERSION,
  SourceManagementError,
  type CreateSourceManagementOptions,
  type InitializeSourceManifestResult,
  type SourceAddInput,
  type SourceAddResultV1,
  type SourceDeclarationSummaryV1,
  type SourceDiffRecordV1,
  type SourceDiffResultV1,
  type SourceDiffStatus,
  type SourceListResultV1,
  type SourceManagementErrorCode,
  type SourceManagementPort,
} from './source-management.js';
export {
  initializeSingleProjectQuickstart,
  QUICKSTART_SCHEMA_VERSION,
  type QuickstartInput,
  type QuickstartOptions,
  type QuickstartResultV1,
} from './quickstart.js';
export {
  createBuiltInSourceAdapterRegistry,
  createSourceAdapterRegistry,
  GENERIC_SOURCE_ADAPTER_ID,
  genericSourceAdapter,
  MAX_SOURCE_METADATA_BYTES,
  MAX_SOURCE_METADATA_DEPTH,
  MAX_SOURCE_METADATA_KEYS,
  mediaTypeForGenericKind,
  P2A_SOURCE_ADAPTER_ID,
  p2aSourceAdapter,
  parseSourceAdapterRegistration,
  parseSourceDescriptor,
  parseSourceMetadata,
  parseSourceRetrievalMeaning,
  neutralSourceRetrievalMeaning,
  sourceRetrievalMeaningFromDescriptor,
  SOURCE_ADAPTER_REGISTRATION_VERSION,
  SOURCE_DESCRIPTOR_SCHEMA_VERSION,
  SOURCE_RETRIEVAL_MEANING_SCHEMA_VERSION,
  validatePortableSourceRef,
  validateSourceRetrievalSupersessionGraph,
  validateSourceOriginRange,
  type CreateBuiltInSourceAdapterRegistryOptions,
  type BoundSourceRetrievalMeaningV1,
  type GenericSourceKind,
  type RegisteredMediaType,
  type RegisteredSourceKind,
  type SourceAdapterKindRegistrationV1,
  type SourceAdapterLimitsV1,
  type SourceAdapterNoticeV1,
  type SourceAdapterProjectionEntryV1,
  type SourceAdapterProjectionInputV1,
  type SourceAdapterRegistrationV1,
  type SourceRetrievalSupersessionNodeV1,
  type SourceAdapterRegistry,
  type SourceAdapterResolution,
  type SourceAdapterResolutionInput,
  type SourceAdapterV1,
  type SourceDescriptorV1,
  type SourceDocumentAuthority,
  type SourceDocumentLifecycle,
  type SourceEvidenceKind,
  type SourceMetadataV1,
  type SourceRetrievalMeaningOrigin,
  type SourceRetrievalMeaningV1,
  type SourceOriginRangeV1,
  type SourceRangeMappingV1,
} from './source-adapters.js';
export {
  inspectLocalSourceStatus,
  type LocalSourceManifestStatus,
  type LocalSourceState,
  type LocalSourceStatus,
} from './local-source-status.js';
