export {
  ProjectionError,
  SourceSelectionError,
  SourceDocumentError,
  type ProjectionErrorCode,
  type SourceDocumentErrorCode,
  type SourceSelectionErrorCode,
  type SourceSelectionField,
} from './errors.js';
export {
  createSourceDocument,
  normalizeSourceBody,
  parseSourceDocument,
  renderSourceDocument,
  validateSourceDocument,
} from './source-document.js';
export { createP2aPlanningProjector } from './p2a-planning-projector.js';
export { createP2aExecutionKnowledgeProjector } from './p2a-execution-projector.js';
export {
  createProjectSyncService,
  PROJECT_SYNC_SCHEMA_VERSION,
  ProjectSyncError,
  type CreateProjectSyncServiceOptions,
  type ProjectSyncDecisionCounts,
  type ProjectSyncErrorCode,
  type ProjectSyncFailurePhase,
  type HubProjectSyncInput,
  type LegacyProjectSyncInput,
  type ProjectSyncInput,
  type ProjectSyncPlanEntrySummary,
  type ProjectSyncPlanSummary,
  type ProjectSyncPort,
  type ProjectSyncRecoveryAction,
  type ProjectSyncSanitizationDiagnostics,
  type ProjectSyncSanitizationRuleSummary,
  type ProjectSyncSanitizationSource,
  type ProjectSyncSummary,
  type ProjectSyncWarning,
  type ProjectSyncWriteSummary,
} from './sync.js';
export { MAX_SYNC_SANITIZATION_DIAGNOSTIC_SOURCES } from './sync-sanitization-diagnostics.js';
export {
  EXECUTION_INCLUSION_POLICY_VERSION,
  EXECUTION_PROJECTION_PLAN_SCHEMA_VERSION,
  type CanonicalTaskLineage,
  type CreateP2aExecutionProjectorOptions,
  type ExecutionDecision,
  type ExecutionExcludeReason,
  type ExecutionIncludeReason,
  type ExecutionKnowledgeProjectorPort,
  type ExecutionProjectionApplyResult,
  type ExecutionProjectionInput,
  type ExecutionProjectionPlan,
  type ExecutionProjectionPlanEntry,
  type ExecutionProjectionWriteResult,
  type ExecutionQuarantineReason,
  type ExecutionReasonCode,
} from './execution-types.js';
export {
  type P2aArtifactAdapter,
  type P2aArtifactBinding,
  type P2aPlanningCandidate,
  type P2aPlanningSelection,
} from './p2a-artifacts.js';
export {
  PROJECTION_PLAN_SCHEMA_VERSION,
  type CreateP2aPlanningProjectorOptions,
  type PlanningDocumentKind,
  type P2aCompatibilityWarning,
  type P2aCompatibilityWarningCode,
  type PlanningProjectionInput,
  type PlanningProjectorPort,
  type ProjectionApplyResult,
  type ProjectionDecision,
  type ProjectionPlan,
  type ProjectionPlanEntry,
  type ProjectionReasonCode,
  type ProjectionWriteResult,
  type ProjectionWriteStatus,
  type RevisionTimestampPort,
  type RevisionTimestampRequest,
  type RevisionTimestampResolution,
  type TimestampSource,
} from './planning-types.js';
export {
  MAX_SOURCE_BODY_CHARS,
  SOURCE_DOCUMENT_SCHEMA_VERSION,
  SOURCE_DOCUMENT_V2_SCHEMA_VERSION,
  SOURCE_DOCUMENT_V3_SCHEMA_VERSION,
  MAX_SOURCE_ORIGIN_MAPPINGS,
  type BuildLoreSourceMetadata,
  type CreateSourceDocumentInput,
  type SourceDocument,
  type SourceType,
} from './types.js';
export {
  MAX_SOURCE_DECLARATIONS,
  MAX_SOURCE_MANIFEST_BYTES,
  MAX_SOURCE_PATH_LENGTH,
  SOURCE_COLLECTION_MANIFEST_SCHEMA_VERSION,
  SOURCE_COLLECTION_MANIFEST_V2_SCHEMA_VERSION,
  parseAnySourceCollectionManifest,
  parseSourceCollectionManifest,
  parseSourceCollectionManifestV2,
  sourceDeclarationDocumentKind,
  validateSourceSelectionPath,
  type AnySourceDeclaration,
  type SourceCollectionManifest,
  type SourceCollectionManifestV1,
  type SourceCollectionManifestV2,
  type SourceDeclaration,
  type SourceDocumentKind,
  type SourceDirectoryDeclaration,
  type SourceFileDeclaration,
  type SourceFileDeclarationV2,
  type SourceDirectoryDeclarationV2,
  type SourceDeclarationV2,
} from './source-manifest.js';
export {
  createSourceManagement,
  initializeSourceManifest,
  inspectSourceManifestInitialization,
  SOURCE_MANAGEMENT_SCHEMA_VERSION,
  SourceManagementError,
  type CreateSourceManagementOptions,
  type InitializeSourceManifestResult,
  type SourceAddInput,
  type SourceAddResultV1,
  type SourceDeclarationSummaryV1,
  type SourceDiffRecordV1,
  type SourceDiffResultV1,
  type SourceDiffStatus,
  type SourceListResultV1,
  type SourceManagementErrorCode,
  type SourceManagementPort,
} from './source-management.js';
export {
  initializeSingleProjectQuickstart,
  QUICKSTART_SCHEMA_VERSION,
  type QuickstartInput,
  type QuickstartOptions,
  type QuickstartResultV1,
} from './quickstart.js';
export {
  createSourceCollectionAdapter,
  createBuiltInSourceAdapterRegistry,
  createSourceAdapterRegistry,
  GENERIC_SOURCE_ADAPTER_ID,
  genericSourceAdapter,
  JSON_SOURCE_ADAPTER_ID,
  jsonSourceAdapter,
  createJsonProjectionSourceAdapter,
  JSON_PROJECTION_CONTRACT_VERSION,
  JSON_EXTRACTION_PROFILE_SCHEMA_VERSION,
  JSON_KNOWLEDGE_ADAPTER_CONTRACT_VERSION,
  MAX_JSON_EXTRACTION_PROFILES,
  MAX_JSON_PROFILE_SECTIONS,
  MAX_JSON_ADAPTER_CANDIDATES,
  jsonValueAtPointer,
  parseJsonExtractionProfile,
  parseJsonExtractionProfiles,
  renderJsonExtractionProfile,
  selectJsonExtractionProfile,
  registerJsonKnowledgeAdapter,
  projectSelectedJsonSource,
  MAX_SOURCE_METADATA_BYTES,
  MAX_SOURCE_METADATA_DEPTH,
  MAX_SOURCE_METADATA_KEYS,
  mediaTypeForGenericKind,
  P2A_SOURCE_ADAPTER_ID,
  P2A_RUN_SOURCE_ADAPTER_ID,
  p2aRunJsonKnowledgeAdapter,
  p2aSourceAdapter,
  sourceAdapterRegistrationDigest,
  parseSourceAdapterRegistration,
  parseSourceDescriptor,
  parseSourceMetadata,
  parseSourceRetrievalMeaning,
  neutralSourceRetrievalMeaning,
  sourceRetrievalMeaningFromDescriptor,
  SOURCE_ADAPTER_REGISTRATION_VERSION,
  SOURCE_DESCRIPTOR_SCHEMA_VERSION,
  SOURCE_DESCRIPTOR_V2_SCHEMA_VERSION,
  SOURCE_RETRIEVAL_MEANING_SCHEMA_VERSION,
  validatePortableSourceRef,
  validateJsonPointer,
  validateSourceRetrievalSupersessionGraph,
  validateSourceOriginRange,
  type CreateBuiltInSourceAdapterRegistryOptions,
  type CreateSourceCollectionAdapterOptions,
  type CollectionCandidate,
  type BoundSourceRetrievalMeaningV1,
  type GenericSourceKind,
  type JsonCollectionCandidate,
  type JsonSourceProjectionInput,
  type AppliedJsonExtractionProfileV1,
  type JsonArrayMode,
  type JsonExtractionProfileV1,
  type JsonProfileMatchV1,
  type JsonProfileProjection,
  type JsonProfileSectionV1,
  type JsonProfileSortV1,
  type JsonProfileTitleV1,
  type JsonScalar,
  type JsonKnowledgeAdapterCandidateDraftV1,
  type JsonKnowledgeAdapterEntryV1,
  type JsonKnowledgeAdapterEntryDecisionV1,
  type JsonKnowledgeAdapterInputV1,
  type JsonKnowledgeAdapterOriginDraftV1,
  type JsonKnowledgeAdapterProjectionV1,
  type JsonKnowledgeAdapterV1,
  type RegisteredJsonKnowledgeAdapterV1,
  type RegisteredMediaType,
  type RegisteredSourceKind,
  type SourceAdapterKindRegistrationV1,
  type SourceAdapterLimitsV1,
  type SourceAdapterNoticeV1,
  type SourceAdapterProjectionEntryV1,
  type SourceAdapterProjectionInputV1,
  type SourceAdapterRegistrationV1,
  type SourceRetrievalSupersessionNodeV1,
  type SourceAdapterRegistry,
  type SourceAdapterResolution,
  type SourceAdapterResolutionInput,
  type SourceAdapterV1,
  type SourceCollectionAdapter,
  type SourceCollectionAdapterInput,
  type SourceCollectionAdapterResult,
  type SourceDescriptorV1,
  type SourceDescriptorV2,
  type SourceDescriptor,
  type SourceDocumentAuthority,
  type SourceDocumentLifecycle,
  type SourceEvidenceKind,
  type SourceMetadataV1,
  type SourceRetrievalMeaningOrigin,
  type SourceRetrievalMeaningV1,
  type SourceOriginRangeV1,
  type SourceJsonOriginMappingV1,
  type SourceJsonOriginV1,
  type SourceInputBindingV1,
  type SourceProfileBindingV1,
  type SourceRangeMappingV1,
} from './source-adapters.js';
export {
  inspectLocalSourceStatus,
  type LocalSourceManifestStatus,
  type LocalSourceState,
  type LocalSourceStatus,
} from './local-source-status.js';
