export {
  createSourceCollectionAdapter,
  type CollectionCandidate,
  type CreateSourceCollectionAdapterOptions,
  type SourceCollectionAdapter,
  type SourceCollectionAdapterInput,
  type SourceCollectionAdapterResult,
  type SourceAdapterProjectionInputV1,
  type SourceAdapterProjectionEntryV1,
  type SourceAdapterNoticeV1,
  type SourceAdapterV1,
} from './collection-adapters.js';
export {
  createBuiltInSourceAdapterRegistry,
  createSourceAdapterRegistry,
  GENERIC_SOURCE_ADAPTER_ID,
  genericSourceAdapter,
  mediaTypeForGenericKind,
  P2A_SOURCE_ADAPTER_ID,
  p2aSourceAdapter,
  type CreateBuiltInSourceAdapterRegistryOptions,
  type SourceAdapterRegistry,
  type SourceAdapterResolution,
  type SourceAdapterResolutionInput,
  type SourceAdapterDefinitionV1,
} from './source-adapter-registry.js';
export {
  MAX_SOURCE_METADATA_BYTES,
  MAX_SOURCE_METADATA_DEPTH,
  MAX_SOURCE_METADATA_KEYS,
  parseSourceAdapterRegistration,
  parseSourceDescriptor,
  parseSourceMetadata,
  SOURCE_ADAPTER_REGISTRATION_VERSION,
  SOURCE_DESCRIPTOR_SCHEMA_VERSION,
  validatePortableSourceRef,
  validateSourceOriginRange,
  type GenericSourceKind,
  type RegisteredMediaType,
  type RegisteredSourceKind,
  type SourceAdapterKindRegistrationV1,
  type SourceAdapterLimitsV1,
  type SourceAdapterRegistrationV1,
  type SourceDescriptorV1,
  type SourceMetadataV1,
  type SourceOriginRangeV1,
  type SourceRangeMappingV1,
} from './source-contracts.js';
